### ISSUE TITLE
Passwords to database contain new line character at the end

### ISSUE THREAD

**Issue by zaycker** [verize/kubernetes-wordpress-ingress#1]
**Own changes from master:**
I used official wordpress and mariadb repository instead of bitnami.

**Result:**
WP container could not connect to database.
Checked from console of database container with `mysql ...` command and had got no luck too.
Checked `env` and saw that there is an empty line after the passwords env variables.

Maybe it is not critical and helps to force people change default password. Don't know the priority. But `RGVtbzEyMzQ1IQo=` is `Demo12345!\n`. And `RGVtbzEyMzQ1IQ==` is exactly `Demo12345!` ^_^

**Comment by gonzaloplaza** [comment]
Fixed , thank you :)
